remote_theme: mmistakes/minimal-mistakes@4.16.5

title: WeatherLink Real-time Data Feed

url: "https://weatherlink.github.io"
baseurl: /real-time-data-feed

search: false

after_footer_scripts:
  - /assets/js/author.js
  - /assets/js/footer-copyright.js

include:
  - _pages

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

plugins:
  - jekyll-include-cache
