remote_theme: mmistakes/minimal-mistakes@4.16.6

title: WeatherLink Real-time Data Feed

url: "https://weatherlink.github.io"
baseurl: /real-time-data-feed

search: false

after_footer_scripts:
  - /assets/js/author.js
  - /assets/js/footer-copyright.js

include:
  - _pages

# Defaults
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: "navMain"

plugins:
  - jekyll-include-cache
